name: MongoDB Direct Integration Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on a push to the main branch

jobs:
  mongodb-integration:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:  # Environment variables for MongoDB connection
      MONGO_URI: ${{ secrets.MONGO_URI }} # MongoDB connection URI stored securely in GitHub Secrets
      MONGO_DB: "my_database"             # Database name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Run Python script
        run: python mongo_script.py
