name: MongoDB CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  mongodb-ci:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Wait for MongoDB to start
      run: |
        echo "Waiting for MongoDB service to start"
        for i in {1..10}; do
          if nc -z localhost 27017; then
            echo "MongoDB is ready"; exit 0
          fi
          echo "MongoDB not ready, retrying..."; sleep 3
        done
        echo "MongoDB did not start in time"; exit 1
    - name: Fetch MongoDB Collections
      run: |
        echo "Fetching all collections from 'my_database' database"
        docker exec $(docker ps -q --filter "ancestor=mongo:5.0") mongo my_database --eval "db.getCollectionNames()" > collections.txt
        echo "Collections fetched from MongoDB:"
        cat collections.txt
