name: MongoDB CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: "mongodb://localhost:27017"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

     

      - name: Seed MongoDB
        run: python app/seed.py

      - name: Test listing entries
        run: python app/app.py
